(Source ../spin-templates/native)
(Cfg_str project_name"Dune Rely Demo")
(Cfg_str project_slug dune-rely-demo)
(Cfg_str project_description"")
(Cfg_str syntax Reason)
(Cfg_str package_manager Esy)
(Cfg_str test_framework Rely)
(Cfg_str ci_cd None)
(Cfg_str author_name"Thibaut Mattio")
(Cfg_str github_username tmattio)